name: Build PrimeSync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List icons directory
      run: dir icons
    - name: Check for icon.ico
      run: |
        if (-not (Test-Path "icons/icon.ico")) {
          Write-Output "icon.ico not found!"
          exit 1
        }
      shell: powershell
    - name: Build with PyInstaller
      run: python build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PrimeSync-Windows
        path: dist/PrimeSync*

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List icons directory
      run: ls -la icons
    - name: Check for icon.icns
      run: |
        if [ -f "icons/icon.icns" ]; then
          echo "icon.icns found!"
        else
          echo "icon.icns not found! Listing all files with similar names..."
          find icons -iname "icon.icns"
          exit 1  # Fail the build to ensure the icon file is added
        fi
    - name: Build with PyInstaller
      run: python build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PrimeSync-macOS
        path: dist/PrimeSync*